- cmd/channel/consolidated/dispatcher/main.go
- config/channel/consolidated/roles/dispatcher-clusterrole.yaml
- pkg/channel/consolidated/kafka/admin.go
- pkg/channel/consolidated/kafka/admin_test.go
- pkg/channel/consolidated/reconciler/controller/consumer_group_watcher.go
- pkg/channel/consolidated/reconciler/controller/consumer_group_watcher_test.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel_test.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
- pkg/channel/consolidated/reconciler/testing/kafkachannel.go
- pkg/common/consumer/consumer_factory.go
- pkg/common/consumer/consumer_factory_test.go
- pkg/common/consumer/consumer_handler.go
- pkg/common/consumer/consumer_handler_test.go
- pkg/source/reconciler/source/resources/labels.go
- pkg/source/reconciler/source/resources/labels_test.go
- test/e2e/helpers/kafka_helper.go
various backports from upstream/release-0.19 branch
> [0.19] Backports from upstream

- openshift/ci-operator/update-ci.sh
> Fixing the CI generator script

- pkg/source/adapter/adapter.go
bringing two upstream PRs to here...
> Backporting 239 and 273 from upstream

- openshift/e2e-common.sh
applying a change from upstream to our own CI setup / execution
> fixing SYSTEM_NAMESPACE stuff

- openshift/patches/001-ignore_deprecated_deployment.patch
- openshift/release/update-to-head.sh
> Adding patch to remove an irelevant deployment

- Makefile
> Update make file

- openshift/e2e-common.sh
> [HEAD] Test with our images from the build

- openshift/ci-operator/update-ci.sh
> Like eventing, script adding reporter_config to periodics

- pkg/common/consumer/consumer_factory.go
* Fix #342
* Commit mistake
(cherry picked from commit b7ca3d0399899f64155b66e6dd2c2a66e915e433)
> Fix race on error channel in consumer factory (#364)

- pkg/channel/consolidated/utils/util.go
- pkg/source/client.go
porting https://github.com/knative-sandbox/eventing-kafka/pull/378  to our fork
> Fixing the TLS bug for using public certs

- README.md
- openshift/release/create-release-branch.sh
- openshift/release/update-to-head.sh
/assign @lberk 
/assign @markusthoemmes 
Feel free to review
> Rename to branch to main

- openshift/e2e-common.sh
> Using matching eventing for tests

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> Use KnativeEventing for the tracing, and patch it, not replace

- openshift/ci-operator/build-image/Dockerfile
- openshift/e2e-common.sh
> [0.20] Use the latest version of product offering

- openshift/e2e-common.sh
> [MAIN] Use the latest version of product offering

- openshift/e2e-common.sh
> [0.21] Using serverless 1.13 

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> Clean-up and use proper eventing via operator

- openshift/e2e-common.sh
- openshift/e2e-tests.sh
> [0.21] Use eventing from operator 0.21

- openshift/release/knative-eventing-kafka-channel-ci.yaml
> [0.21] Update generated yamls 0.21

- pkg/channel/consolidated/reconciler/controller/controller.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/lister.go
- pkg/channel/consolidated/status/status.go
- pkg/channel/consolidated/status/status_test.go
Backport of Update target pod IPs when dispatcher pods scale (knative-sandbox/eventing-kafka#496)
> [v0.20.0] Backport of Update target pod IPs when dispatcher pods scale (knative-sandbox/eventing-kafka#496)

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
- pkg/channel/consolidated/dispatcher/dispatcher_test.go
- pkg/channel/consolidated/dispatcher/kafka_subscription.go
- pkg/channel/consolidated/reconciler/dispatcher/kafkachannel.go
> Backported #509

- openshift/e2e-common.sh
> Fixing the registry... once more

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/status/status.go
Signed-off-by: Ahmed Abdalla <aabdelre@redhat.com>
backporting #551 to our 0.20 branch
> [0.20] Only return true in probe verifier if all partitions found

- test/upgrade/continual.go
- test/upgrade/suite.go
Cherry pick of knative-sandbox#540
> [0.21] Setting retries & replication options with easy customization

- test/upgrade/continual.go
- test/upgrade/suite.go
Cherry pick of knative-sandbox#540
> [0.22] Setting retries & replication options with easy customization

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
backport of https://github.com/knative-sandbox/eventing-kafka/pull/565  to our branch
> [0.22] Missing defer close kafka admin client

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
backport of https://github.com/knative-sandbox/eventing-kafka/pull/565  to our branch
> [0.21] Missing defer close kafka admin client

- openshift/e2e-common.sh
like #104 but move the rest of this also to 0.21
> [0.21] Change tracing cfg

- openshift/e2e-common.sh
porting https://github.com/openshift-knative/eventing-kafka/pull/185  to main
> [main] Change tracing cfg

- openshift/e2e-common.sh
porting https://github.com/openshift-knative/eventing-kafka/pull/185  to `0.22`
> [0.22] Change tracing cfg

- pkg/channel/consolidated/reconciler/controller/controller.go
- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/reconciler/controller/lister.go
- pkg/channel/consolidated/status/status.go
- pkg/channel/consolidated/status/status_test.go
- pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/controller.go
- pkg/client/injection/reconciler/bindings/v1alpha1/kafkabinding/reconciler.go
- pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/controller.go
- pkg/client/injection/reconciler/bindings/v1beta1/kafkabinding/reconciler.go
- pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/controller.go
- pkg/client/injection/reconciler/messaging/v1alpha1/kafkachannel/reconciler.go
- pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/controller.go
- pkg/client/injection/reconciler/messaging/v1beta1/kafkachannel/reconciler.go
- pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/controller.go
- pkg/client/injection/reconciler/sources/v1alpha1/kafkasource/reconciler.go
- pkg/client/injection/reconciler/sources/v1beta1/kafkasource/controller.go
- pkg/client/injection/reconciler/sources/v1beta1/kafkasource/reconciler.go
bringing https://github.com/knative-sandbox/eventing-kafka/commit/fece5fa897dace4fbe621666ca6237b8c7b2b7a3  to our 0.21 release branch
> [v0.21] Backport of upstream #497

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/status/status.go
Backporting 
* https://github.com/knative-sandbox/eventing-kafka/pull/553
* https://github.com/knative-sandbox/eventing-kafka/pull/558
to our 0.21 fork's branch....
> [0.21] Backport 553 and 558

- openshift/e2e-common.sh
> [0.22] Using the Serverless 1.15 product

- vendor/knative.dev/pkg/webhook/certificates/certificates.go
- vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
- vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
As per title. To fix FIPS related issues.
/hold
To determine if we want this.
> [RELEASE-v0.20.0] Rollback certificate algorithm changes

- vendor/knative.dev/pkg/webhook/certificates/certificates.go
- vendor/knative.dev/pkg/webhook/certificates/resources/certs.go
- vendor/knative.dev/pkg/webhook/certificates/resources/secret.go
> Rollback certificate algorithm changes (#212)

- pkg/common/consumer/consumer_handler.go
Signed-off-by: Ahmed Abdalla <aabdelre@redhat.com>
> Cancel dispatching messages when consumer group session is closed (#661)

- pkg/common/consumer/consumer_handler.go
Backport from upstream knative-sandbox/eventing-kafka#662
> [release-v0.22.0] Cancel dispatching messages when consumer group session is closed (#662)

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/update-ci.sh
> Fixing some scripts for 0.23 (and later)

- openshift/release/mirror-upstream-branches.sh
> Change the name of the mistream release branch to be just X.Y

- openshift/e2e-common.sh
> [main] Bumping to serverless 1.15

- openshift/e2e-common.sh
> [0.23]  Bumping to serverless 1.15

- openshift/release/update-to-head.sh
Correct the org which was changed in https://github.com/openshift-knative/eventing-kafka/commit/77db6bab8ce80573d1a1f67e95ae028b47dc1735
> Use the correct openshift-knative or in syncing PRs

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
- pkg/channel/consolidated/status/status.go
Backporting
knative-sandbox#553
knative-sandbox#558
to our 0.22 fork's branch....
> [0.22] Backport 553 and 558 

- pkg/channel/consolidated/dispatcher/consumer_message_handler.go
- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/testing/mocks.go
- vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
- vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
- vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
Cherry picked https://github.com/openshift-knative/eventing-kafka/pull/234.
@slinkydeveloper afaik this is the right branch v0.23 and not v0.23.0 as discussed with @matzew, correct?
> [Backport][Release-v0.23] Support Eventing metrics

- openshift/e2e-common.sh
> Using 1.16 version of product

- Makefile
- openshift/ci-operator/knative-images/migrate/Dockerfile
> [0.23] Adding kafka source migration image

- openshift/ci-operator/build-image/Dockerfile
backport of https://github.com/openshift-knative/eventing-kafka/pull/433
> [release-v1.0] Golang 1.17 container image (#433)

- openshift/patches/001_quay_kafkacat_replace.patch
> Patch the patched patch :dizzy:

- test/upgrade/continual/kafkasender.go
Co-authored-by: Martin Gencur <mgencur@redhat.com>
> Prevent excessive wait time in KafkaSender for upgrade tests (#1107)

- openshift/ci-operator/build-image/kubernetes.repo
Disable gpg check for Kubernetes Yum repo
> Disable gpg check for Kubernetes Yum repo
