- openshift/e2e-common.sh
- openshift/e2e-tests.sh
- test/config/100-kafka-ephemeral-triple-2.6.0.yaml
TLS/SASL will follow in a new PR 
We need this, so that we can actually bump the serverless operator w/ the 0.19.1 kafkas ....
> Install Knative Kafka and run simple tests (no TLS/SASL)

- openshift/ci-operator/generate-ci-config.sh
- openshift/ci-operator/knative-images/source_controller/Dockerfile
- openshift/ci-operator/update-ci.sh
- openshift/e2e-common.sh
- openshift/e2e-tests.sh
- openshift/release/knative-eventing-kafka-channel-ci.yaml
- openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
- openshift/release/knative-eventing-kafka-source-ci.yaml
- openshift/release/resolve.sh
MASTER is used as `stash` (like on our other forks), and we have now CI enabled on the `019.1` branch. This copies those files here, so we have them, on our master stash.
> Adding more OCP specific files for the master stash

- openshift/ci-operator/update-ci.sh
- openshift/e2e-common.sh
* use new 0.19 images (well, newly added to mirror)
* Adding logic to update the "mirror" file for openshift/releaes repo's quay_io mirror
> [0.19] Update ci script generator

- Makefile
- openshift/ci-operator/knative-test-images/event-sender/Dockerfile
- openshift/ci-operator/knative-test-images/heartbeats/Dockerfile
- openshift/ci-operator/knative-test-images/performance/Dockerfile
- openshift/ci-operator/knative-test-images/print/Dockerfile
- openshift/ci-operator/knative-test-images/recordevents/Dockerfile
the real change against HEAD.... (see: https://github.com/openshift-knative/eventing-kafka/pull/27)
> Adding dependent test images

- openshift/ci-operator/build-image/Dockerfile
Upstream is on 1.15 golang ... see PR: 338
> Using 1.15 on our linux container

- openshift/release/generate-release.sh
- openshift/release/knative-eventing-kafka-channel-ci.yaml
- openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
- openshift/release/knative-eventing-kafka-source-ci.yaml
we should be using the `registry.ci.openshift` url...
I noticed this change, b/c the mirror file uses that ....   
I have to admit that for some time both functioned - not knowing which is the correct .... now we know .
This fix prevents docker pull errors
> Registry update 0.21.0

- openshift/e2e-common.sh
Preparation for separated installs of the two different channels
/assign @lberk
> Explicit names for install functions

- openshift/e2e-common.sh
- openshift/release/knative-eventing-kafka-channel-ci.yaml
* regenerating the yamls (missing content, due to backports touched the source... but not the CI generated yamls), via `make RELEASE=v0.20.0 generate-release`
* removing one more of old registry
> [0.20] More clean up

- openshift/ci-operator/build-image/kubernetes.repo
This is a fix according to kubernetes/kubernetes#60134 . The build image includes GnuPG 2.0.22 which shows this problem.
> [0.19] Disable repo_gpgcheck for kube repo in build image

- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/consolidated/dispatcher/dispatcher_it_test.go
> [0.20] Use CE connection args available, instead of hardcoded values (#440)

- pkg/channel/consolidated/dispatcher/dispatcher.go
Cherry pick https://github.com/knative-sandbox/eventing-kafka/pull/440 into 0.21
> [0.21] Cherrypick - Use CE connection args available, instead of hardcoded values

- pkg/channel/consolidated/reconciler/controller/kafkachannel.go
backport of https://github.com/knative-sandbox/eventing-kafka/pull/565  to our branch
> [0.20] Missing defer close kafka admin client

- openshift/release/knative-eventing-kafka-channel-ci.yaml
- openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
- openshift/release/knative-eventing-kafka-source-ci.yaml
/hold
needs https://github.com/openshift/release/pull/18089  to be merged and in place
Follow up: likely to patch our serverless-operator repo for the `storage` changes (as we are not able to consume that from the automated download via upstream's 0.21.1)
/assign @lberk
> Fixing version of promoted images and the storage fu

- openshift/e2e-common.sh
> [0.20] Use the latest of OCP Serverless on 0.20 branch

- openshift/e2e-common.sh
> [main] Use the latest of OCP Serverless on main branch

- openshift/e2e-common.sh
> [0.21] Use the latest of OCP Serverless on 0.21 branch

- openshift/e2e-common.sh
> [0.22] Use the latest of OCP Serverless on 0.22 branch

- Makefile
- openshift/ci-operator/knative-images/migrate/Dockerfile
We need to build the linux container for the "post install" job. We use the _vendored_ lib for that.
> [0.21] Adding new image for the migrator

- openshift/release/knative-eventing-kafka-channel-ci.yaml
- openshift/release/knative-eventing-kafka-distributed-channel-ci.yaml
- openshift/release/knative-eventing-kafka-source-ci.yaml
images are now promoted as `0.22.3`, via https://github.com/openshift/release/pull/18406
/assign @aliok
> Reflecting version change on the image promotion

- openshift/ci-operator/update-ci.sh
We have added the 4.8 CI runs for kafka. This PR adds those to the CI-Config generator, so we have it for future releases
> [main] adding the 4.8 version to the stash

- openshift/release/create-release-branch.sh
@matzew I think the mirroring script is failing because of the `git fetch upstream --tags` invocation on line 11 here -- it seems that the tags would get clobbered. I'm adding more verbosity here for the nightly runs to see.
I'm not sure I understand if there's any downside to updating the tags from upstream (I'm actually not entirely sure why there's a clobbering issue in general for 0.21 or 0.22 branches).  Any idea if we could add a `-f` to the `git fetch upstream --tags` line?
> Add verbosit to create-release-branch.sh script

- test/upgrade/continual.go
As per title. Compilation is currently broken, which prevents us from bumping the version in serverless-operator.
/assign @cardil
> Fix compilation of upgrade tests

- pkg/source/adapter/adapter.go
Backporting "KafkaSource retries on error (#666)"
> [0.23] Backport of 666

- pkg/channel/consolidated/dispatcher/consumer_message_handler.go
- pkg/channel/consolidated/dispatcher/dispatcher.go
- pkg/channel/distributed/dispatcher/dispatcher/handler.go
- pkg/channel/distributed/dispatcher/testing/mocks.go
- vendor/knative.dev/eventing/pkg/channel/fanout/fanout_message_handler.go
- vendor/knative.dev/eventing/pkg/channel/message_dispatcher.go
- vendor/knative.dev/eventing/pkg/channel/stats_reporter.go
Backport: https://github.com/knative-sandbox/eventing-kafka/pull/688
To be completely aligned opened: https://github.com/openshift/knative-eventing/pull/1311
My goal is to add visualizations for channel metrics at the S-O side.
/cc @aliok @matzew 
I am also planning to backport for 0.23. Didnt go upstream because afaik we depend on the release tag there.
> [Backport][Release-v0.22.0] Support eventing metrics 

- test/e2e/kafka_binding_test.go
we do not care about the `v1alpha1` anyways - it's also already removed, upstream
> [0.23] Remove depracted test

- test/e2e/kafka_binding_test.go
we do not care about the `v1alpha1` anyways - it's also already removed, upstream
> [0.22] Remove depracted test

- openshift/release/mirror-upstream-branches.sh
catch branches on openshift that match v0.X and the previous v.X.Y scheme
related: SRVKE-886
> Update mirroring script branch check due to new naming scheme

- vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go
Done for SRVKS-790 - See #308 for reference
> [0.24] Patch subresource to unblock webhooks on 4.9 (#308)

- openshift/e2e-common.sh
The goal is to move patching the knativeeventing resource from
run_e2e_tests to install_tracing and better separate installation from
running E2E tests.
The run_e2e_tests function is reused in serverless-operator repo and
there we might install tracing earlier. Patching the knativeeventing
resource at that point brakes the installation.
The run_e2e_tests function should really just run tests and not change
product installation.
This is required for https://github.com/openshift-knative/serverless-operator/pull/1453
> [release-v1.1] Patch knative-eventing with tracing config when installing tracing
